services:
  web:
    build: .
    image: iris-prediction
    environment: 
      - FLASK_ENV=${FLASK_ENV}
      - MODEL_PATH=${MODEL_PATH}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
    ports:
      - "8000:5000"
    volumes: 
    - ./app:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "127.0.0.1:8000"]
      interval:  30s
      timeout: 10s
      retries: 3
      start_period: 5s

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test:  ["CMD", "redis-cli", "ping"]
      interval:  30s
      timeout: 10s
      retries: 3