name: Iris-Prediction-App

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout host repository
              uses: actions/checkout@v4

            - name: setting up python version
              uses: actions/setup-python@v4

            - name: installing packages and dependencies 
              run: |
                pip install -r requirements.txt
                pip install pytest 
            
            - name: testing the output
              run: |
                pytest

    build:
        needs: test 
        runs-on: windows-latest
        steps:
            - name: checkout host repository
              uses: actions/checkout@v4

            - name: building image
              uses: docker/setup-buildx-actions@v3

              ## need to add login credential 
              ## from docker to githubactions
            - name: login credentials
              uses: docker/login-actions@v3
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}

            - name: pushing images into docker hub
              uses: docker/build-push-actions@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{secrets.DOCKER_USERNAME}}/iris-prediction-app:latest
            
            - name: digest image
              run: |
                echo "${{steps.build-and-deploy.digest}}"
